In [94]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn import metrics

dataset = pd.read_csv("iphone.csv")
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:, 3].values
display(X)

array([['Male', 19, 19000],
       ['Male', 35, 20000],
       ['Female', 26, 43000],
       ...,
       ['Female', 50, 20000],
       ['Male', 36, 33000],
       ['Female', 49, 36000]], dtype=object)

In [95]:
X[:,0] = np.where(X[:,0] == 'Male', 1, 0)
display(X)

array([[1, 19, 19000],
       [1, 35, 20000],
       [0, 26, 43000],
       ...,
       [0, 50, 20000],
       [1, 36, 33000],
       [0, 49, 36000]], dtype=object)

In [96]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [97]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [98]:
sv_linear_class = SVC(kernel = 'linear')
sv_linear_class.fit(X_train, y_train)
y_pred = sv_linear_class.predict(X_test)

In [99]:
linear_cm = metrics.confusion_matrix(y_test, y_pred) 
print(cm)
linear_accuracy = metrics.accuracy_score(y_test, y_pred) 
print("Accuracy score:",linear_accuracy)
linear_precision = metrics.precision_score(y_test, y_pred) 
print("Precision score:",linear_precision)
linear_recall = metrics.recall_score(y_test, y_pred) 
print("Recall score:",linear_recall)

[[65  3]
 [ 8 24]]
Accuracy score: 0.89
Precision score: 0.8888888888888888
Recall score: 0.75


In [100]:
sv_poly_class = SVC(kernel = 'poly', degree = 2)
sv_poly_class.fit(X_train, y_train)
y_pred = sv_poly_class.predict(X_test)

In [101]:
poly_cm = metrics.confusion_matrix(y_test, y_pred) 
print(cm)
poly_accuracy = metrics.accuracy_score(y_test, y_pred) 
print("Accuracy score:",poly_accuracy)
poly_precision = metrics.precision_score(y_test, y_pred) 
print("Precision score:",poly_precision)
poly_recall = metrics.recall_score(y_test, y_pred) 
print("Recall score:",poly_recall)

[[65  3]
 [ 8 24]]
Accuracy score: 0.76
Precision score: 0.6818181818181818
Recall score: 0.46875


In [102]:
sv_rbf_class = SVC(gamma = 1)
sv_rbf_class.fit(X_train, y_train)
y_pred = sv_rbf_class.predict(X_test)

In [103]:


rbf_cm = metrics.confusion_matrix(y_test, y_pred) 
print(cm)
rbf_accuracy = metrics.accuracy_score(y_test, y_pred) 
print("Accuracy score:",rbf_accuracy)
rbf_precision = metrics.precision_score(y_test, y_pred) 
print("Precision score:",rbf_precision)
rbf_recall = metrics.recall_score(y_test, y_pred) 
print("Recall score:",rbf_recall)

[[65  3]
 [ 8 24]]
Accuracy score: 0.93
Precision score: 0.8787878787878788
Recall score: 0.90625
